# Generated by Django 2.1.5 on 2020-09-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20170928_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekTargetList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_in_number_of_week_cycles', models.IntegerField(null=True)),
                ('day_target_show_from_weekday', models.DateField(default='2020-09-20')),
                ('day_target_show_to_weekday', models.DateField(default='2020-09-20')),
                ('week_target_backlog_item_sorting_category_indistinguishable', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('comment', models.TextField()),
                ('associated_email_received_datetime', models.DateField(default='2020-09-20')),
                ('associated_email_received_account', models.CharField(max_length=250)),
                ('plan_duration_mins', models.IntegerField(null=True)),
                ('recurrence_period_weeks', models.IntegerField(null=True)),
                ('due_datetime', models.DateField(default='2020-09-20')),
                ('status_category', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
