# Generated by Django 2.1.5 on 2020-09-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20200920_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2020-09-22'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2020-09-22'),
        ),
        migrations.AlterField(
            model_name='weektargetlist',
            name='associated_email_received_datetime',
            field=models.DateField(default='2020-09-22'),
        ),
        migrations.AlterField(
            model_name='weektargetlist',
            name='day_target_show_from_weekday',
            field=models.DateField(default='2020-09-22'),
        ),
        migrations.AlterField(
            model_name='weektargetlist',
            name='day_target_show_to_weekday',
            field=models.DateField(default='2020-09-22'),
        ),
        migrations.AlterField(
            model_name='weektargetlist',
            name='due_datetime',
            field=models.DateField(default='2020-09-22'),
        ),
    ]
